import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { Sparkles, ArrowRight } from 'lucide-react';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, PieChart, Pie, Cell, BarChart, Bar } from 'recharts';
import { api, formatQuantity } from '../lib/api';
import { EmptyState, LoadingState } from './app-shell';

type Point = { date: string; receipts: number; deliveries: number; receiptReversals: number; deliveryReversals: number };
type Analytics = { asOf: string; totalProducts: number; health: Record<string, number>; warehouseDistribution: Array<{ id: string; name: string; products: number }>; series: Array<{ id: string; symbol: string; points: Point[] }> };
const healthLabels = [['HEALTHY', 'Healthy', '#2f7251'], ['LOW_STOCK', 'Low stock', '#bd8f32'], ['OUT_OF_STOCK', 'Out of stock', '#b95849']];

export function InventoryAnalytics({ warehouseId, locationId, categoryId }: { warehouseId: string; locationId: string; categoryId: string }) {
  const [days, setDays] = useState(7);
  const [unitId, setUnitId] = useState('');
  const query = useQuery({ queryKey: ['dashboard', 'analytics', warehouseId, locationId, categoryId, days],
    queryFn: () => api<Analytics>(`/dashboard/analytics?${new URLSearchParams({ days: String(days), ...(warehouseId ? { warehouseId } : {}), ...(locationId ? { locationId } : {}), ...(categoryId ? { categoryId } : {}) })}`) });
  const series = query.data?.series.find(s => s.id === unitId) ?? query.data?.series[0];
  const health = healthLabels.map(([key, name, color]) => ({ name, value: query.data?.health[key] ?? 0, color }));
  return <section className="analytics-section" aria-label="Inventory analytics">
    <div className="analytics-heading"><div><span className="eyebrow">Inventory intelligence</span><h2>The bigger picture</h2></div><div className="segmented" aria-label="Movement period">{[7, 30].map(period => <button key={period} aria-pressed={days === period} onClick={() => setDays(period)}>Last {period} days</button>)}</div></div>
    <p className="filter-explainer">Current stock follows warehouse, location and category. Movement trends show finalized receipts and deliveries by UTC day; document type/status filters do not hide this history.</p>
    {query.isPending ? <LoadingState /> : query.isError ? <EmptyState title="Analytics unavailable" message={query.error.message} action={<button className="button" onClick={() => void query.refetch()}>Retry analytics</button>} /> : <>
      <div className="analytics-grid"><article className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">Finalized movement</span><h2>Inventory Movement</h2></div>{series && <select aria-label="Movement unit" value={series.id} onChange={event => setUnitId(event.target.value)}>{query.data.series.map(unit => <option value={unit.id} key={unit.id}>{unit.symbol}</option>)}</select>}</div>
        {series ? <><div className="chart-canvas"><ResponsiveContainer width="100%" height="100%"><LineChart data={series.points} margin={{ top: 12, right: 20, left: 0, bottom: 0 }} accessibilityLayer><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e7e9e1" /><XAxis dataKey="date" tickFormatter={v => String(v).slice(5)} tick={{ fontSize: 11 }} minTickGap={28} /><YAxis tick={{ fontSize: 11 }} width={55} /><Tooltip formatter={value => `${formatQuantity(Number(value))} ${series.symbol}`} /><Legend wrapperStyle={{ fontSize: 11 }} /><Line type="monotone" dataKey="receipts" name="Receipts" stroke="#2f7251" strokeWidth={2} dot={false} /><Line type="monotone" dataKey="deliveries" name="Deliveries" stroke="#bd8f32" strokeWidth={2} dot={false} /><Line dataKey="receiptReversals" name="Receipt reversals (out)" stroke="#b95849" strokeDasharray="4 3" dot={false} /><Line dataKey="deliveryReversals" name="Delivery reversals (in)" stroke="#637d88" strokeDasharray="4 3" dot={false} /></LineChart></ResponsiveContainer></div>
        <details className="chart-data"><summary>View exact movement values</summary><div className="table-wrap"><table><thead><tr><th>UTC date</th><th>Receipts</th><th>Deliveries</th><th>Receipt reversals</th><th>Delivery reversals</th></tr></thead><tbody>{series.points.map(p => <tr key={p.date}><td>{p.date}</td>{[p.receipts, p.deliveries, p.receiptReversals, p.deliveryReversals].map((v, i) => <td key={i}>{formatQuantity(v, series.symbol)}</td>)}</tr>)}</tbody></table></div></details></> : <EmptyState title="No movement in this period" message="Completed receipts and deliveries will appear here. Different units are never added together." />}
        <p className="chart-note">Reversals remain visible as separate series. Net = receipts − deliveries − receipt reversals + delivery reversals.</p>
      </article><article className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">Current balances</span><h2>Stock Health</h2></div></div>
        {query.data.totalProducts ? <><div className="health-chart"><ResponsiveContainer width="100%" height={210}><PieChart accessibilityLayer><Pie data={health} dataKey="value" nameKey="name" innerRadius={62} outerRadius={83} paddingAngle={2}>{health.map(item => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="donut-center"><strong>{query.data.totalProducts}</strong><span>products</span></div></div><ul className="health-legend">{health.map(item => <li key={item.name}><span style={{ background: item.color }} />{item.name}<strong>{item.value}</strong></li>)}</ul></> : <EmptyState title="No products in scope" message="Add products or broaden the category filter." />}
      </article></div>
      <article className="panel chart-panel warehouse-chart"><div className="panel-heading"><div><span className="eyebrow">Network footprint</span><h2>Warehouse Distribution</h2></div><span className="table-sub">Distinct stocked products · not mixed-unit quantities</span></div>{query.data.warehouseDistribution.length ? <><div style={{ height: Math.max(170, query.data.warehouseDistribution.length * 42), maxHeight: 480, overflowY: 'auto' }}><ResponsiveContainer width="100%" height={Math.max(170, query.data.warehouseDistribution.length * 42)}><BarChart data={query.data.warehouseDistribution} layout="vertical" margin={{ left: 8, right: 32 }} accessibilityLayer><CartesianGrid horizontal={false} stroke="#e7e9e1" /><XAxis type="number" allowDecimals={false} /><YAxis type="category" dataKey="name" width={135} tick={{ fontSize: 11 }} /><Tooltip /><Bar dataKey="products" name="Stocked products" fill="#2f7251" radius={[0, 4, 4, 0]} maxBarSize={22} /></BarChart></ResponsiveContainer></div><p className="chart-note">{query.data.warehouseDistribution.map(w => `${w.name}: ${w.products}`).join(' · ')}</p></> : <EmptyState title="No warehouse in scope" message="Create a warehouse in Inventory Setup or adjust the filters." />}</article>
    </>}
    <article className="ai-entry-card"><div className="ai-mark"><Sparkles size={24} /></div><div><span className="eyebrow">StockSense AI</span><h2>Ask your inventory what needs attention.</h2><p>Explore live stock, movement history and practical transfer opportunities.</p><div className="ai-quick-actions">{['Analyze low stock', 'Find transfer opportunities', 'What needs attention today?'].map(question => <Link key={question} to={`/ai?q=${encodeURIComponent(question)}`}>{question}<ArrowRight size={14} /></Link>)}</div></div></article>
  </section>;
}
